/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{js,ts,jsx,tsx}", "./public/assets/icons/**/*.{svg}"],
    theme: {
        extend: {
            backgroundImage: {
                welcome: "url('/assets/images/l234k.png')",
            },
            spacing: {
                2: '2px',
                4: '4px',
                6: '6px',
                8: '8px',
                10: '10px',
                12: '12px',
                13: '13px',
                14: '14px',
                16: '16px',
                18: '18px',
                20: '20px',
                22: '22px',
                24: '24px',
                26: '26px',
                28: '28px',
                30: '30px',
                32: '32px',
                34: '34px',
                36: '36px',
                38: '38px',
                40: '40px',
                42: '42px',
                44: '44px',
                46: '46px',
                48: '48px',
                50: '50px',
                52: '52px',
                54: '54px',
                56: '56px',
                58: '58px',
                60: '60px',
                62: '62px',
                64: '64px',
                66: '66px',
                68: '68px',
                70: '70px',
                72: '72px',
                74: '74px',
                76: '76px',
                78: '78px',
                80: '80px',
                82: '82px',
                84: '84px',
                86: '86px',
                88: '88px',
                90: '90px',
                92: '92px',
              },
            colors: {
                primary: "#ffc700",
                secondary: "#000124",
            },
            fontFamily: {
                display: ["Gilroy"],
                body: ["Montserrat"],
            },
            fontSize: {
                base: ["16px", "20px"],
                display: ["60px", "71px"],
            },
        },
    },
    plugins: [],
};
